language: ruby
rvm:
- 1.9.3
before_script:
- gem install bundler
- bundle install
script: bundle exec jekyll build
install: bundle install
after_success: bundle exec s3_website push
env:
  global:
  - secure: me4wuUXy4lCp++j97mbD5yN8iGyWbVHMFeN9tRMldTDyfNytBoMWyuJDTMHdfFR9O6p4unjb7ZtGxVSBgTnhZDnkZWU8x9CAEStiCQx/8PXJ7aRbh1na9IVVRFMh65PjPEyJQHsaFLxQIuD5R3i7PYL0ExPVLCz5KGgTGYln0VI=
  - secure: bHhWqJM84emojzui9RPVhkNBaa1ayZDJN/4yMd/3DYXu8kzPA/HtJ1Dj3YUIVGFAdVIB3fmtpFoZY3Eg52xxjEZLIkpX+bHHz/KcubqLZGRySnkQFNz7UHx/6fO6msSceOVzt54ROSzD4GQ1ZH5RiWKSE8De+OtAWm2+pdcq0U0=
  - secure: rPhj1KX2OY+RZfOWoDb9bEa2VhuvSwyvleiYIQXBK6umG0OYi4/fiRIuD4ve0C7adV9/KnA1elzLVYj+h1/Kb+01766UAknhRVqOKcpQfJXKkIpzwwTH6zqxyWFJogv2aYbEw9ysj6Ivjj0vRtemYWMNLNfGlU/lX6z/LHWPe1g=
