# Site settings
title: 2 Headed Squirrel
email: andrew.ruestow@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is where the stuff happens, 2 Headed Squirrel stuff!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://2headedsquirrel.com" # the base hostname & protocol for your site
twitter_username: 2headedsquirl
github_username:  reustonium

# Build settings
markdown: kramdown
highlighter: rogue
